### ISSUE TITLE
Token Patch Size?

### ISSUE THREAD

**Issue by starsong98** [scaling-diffusion-perception/scaling-diffusion-perception#2]
Hello. Thank you for releasing your amazing paper.

What patch size did you use for each token in your DiT-XL models? I could not find the number in the paper. Is it 2, like with your other experiments involving DiT-S/2 and DiT-L/2 models?

**Comment by zpx01** [comment]
Hi! We used a patch size of 2 for our DiT-XL models. We plan to release the inference code and model checkpoints in a few weeks once we have more bandwidth. Thank you for your patience!
